# ConfigMap for Prometheus configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |-
    global:
      scrape_interval: 15s
    scrape_configs:
    - job_name: 'petstore'
      static_configs:
      - targets: ['petstore-handler-service:8080'] # Update with your service names
    - job_name: 'prometheus'
      static_configs:
      - targets: ['localhost:9090']  # Scraping Prometheus itself
