FROM golang:1.22-alpine AS builder

WORKDIR /app

# Copy the project files
COPY go.mod go.sum ./
RUN go mod download

COPY . .

# Build the application 
RUN CGO_ENABLED=0 GOOS=linux go build -o storage-service cmd/storage/main.go

# Final stage (using a smaller image)
FROM alpine:latest

WORKDIR /app

# Copy the binary from the builder stage
COPY --from=builder /app/storage-service .
COPY ./cert ./cert

# Expose the port
EXPOSE 8081

# Command to run
CMD ["./storage-service"]