apiVersion: batch/v1
kind: Job
metadata:
  name: petstore-storage-service-migrations
spec:
  template:
    spec:
      containers:
      - name: petstore-storage-service-migrations
        image: us.icr.io/vizvasrj/petstore-storage-service-migrations:1
        env:
          - name: POSTGRES_USER 
            valueFrom: 
              secretKeyRef:
                name: postgres-secrets
                key: username
          - name: POSTGRES_PASSWORD 
            valueFrom:
              secretKeyRef:
                name: postgres-secrets
                key: password
          - name: POSTGRES_HOST
            value: postgres-service
          - name: POSTGRES_DB
            value: petstore
          - name: POSTGRES_PORT
            value: "5432"
          - name: POSTGRES_SSLMODE
            value: disable
      restartPolicy: Never
  backoffLimit: 4